const item = {
    items: [
        "1/4 x 6 Toolbits",
        "12 X 1/2 x 18 TPI HSS Hacksaw Blades",
        "12 x 1/2 x 24 TPI HSS Hacksaw Blades",
        "18 x 1.1/4 x 4 TPI HSS Hacksaw Blades",
        "18 x 1.1/4 x 6 TPI HSS Hacksaw Blades",
        "5/16 x 6 Toolbits",
        "Abradur 6764 HRA Size 4.00mm",
        "Adhesive Paste - Camlin",
        "Ador 70S2 Size: 2.4mm",
        "Aircut 150i",
        "Aluminium Brazing Rods",
        "Aluminium Track",
        "Angle Grinder Dewalt",
        "Anti Spatter 702 Chemlube",
        "Aradur HY 951",
        "Araldite CY 205",
        "Araldite Standard 90gm",
        "Araldite Std 180gm",
        "Araldite Std 36gm",
        "Argon Rod / Tungsten Electrode 2.4mm",
        "Argon Tig Rod - 4mm",
        "Black Glass for Welding",
        "Blow Pipe - Gas Cutting Gasco",
        "Bonderite L-FM PL 101 30 Ltrs",
        "Boss 396 Clear 270ml",
        "Boss Pu 25 Black 600ml",
        "Boss Unversal PU Foam 750ml",
        "Bronzocar-32 (AC) Size 4.00mm",
        "Bulbond Pouch - 1 Kg",
        "CCMS Filler Wire",
        "COLLET 4.00MM",
        "CRCN-60 Size 4.00mm",
        "CUMI MICROCUT 719-200 LTRS",
        "Carbide Tip Tool",
        "Castodyne- 2386 Size- 3.15mm",
        "Cathod",
        "Ceramic Nozzle",
        "Chain Saw",
        "Chain Saw Machine",
        "Chamfertic Size : 3.15mm",
        "Cimstar MB 602C - 35 Ltr",
        "Conical Nozzle Big",
        "Cumi Micro S930 - 200 Ltr",
        "Cumi Micro S930 - 35 Ltrs",
        "Cumizing Premium Zirconia 100x16 Grit -36",
        "Cutting Nozzle",
        "Cylinder Key",
        "Cylinder Nut",
        "DPC Set",
        "Dead Center",
        "Diaphragm",
        "Die Grinder",
        "Diffuser",
        "Dog Chuck",
        "Dowsil 1080 - 100 Gms Pack",
        "Dowsil 1080 Clear- 300MI",
        "Ecostar 306 - 200 Ltrs",
        "Electrode ( EL 250W )",
        "Electrode Plasma - 120 Amps Warpp",
        "Electrode Plasma - 200 Amps Warpp",
        "End Mill",
        "FAG Bearing N315-EM1-C3",
        "FLUX CORED WIRE 1.2 SS 309L (STRONG)",
        "FLUXCORED WIRE 1.2 SS E308L (STRONG)",
        "FRONT CAP FC-120 A",
        "Fag Bearing 6202-2Z-C3",
        "Fan",
        "Fevico Woodfin Oak Yellow - 500ml",
        "Fevicol Ezee Spray",
        "Fevicol Heatex 100 Ml",
        "Fevicol Heatex 1Ltr",
        "Fevicol Heatex 200ml",
        "Fevicol Heatex 500 Ml",
        "Fevicol Hi-Per 800 Gm Pouch",
        "Fevicol Marine - 800 Gm Pouch",
        "Fevicol Nailfree Ultra",
        "Fevicol Probond 1Kg",
        "Fevicol SH 50 Gm",
        "Fevicol SH 500gm",
        "Fevicol SR 998 100ml",
        "Fevicol SR 998 200ml",
        "Fevicol SR 998 FW - 5 Ltr",
        "Fevicol Sh 125gm",
        "Fevicol Sh 250gm",
        "Fevicol Woodfin Oak Yellow - 1 Ltr",
        "Feviol Hiper Star 800 Pouch",
        "Feviseal GP Pro Black",
        "Feviseal Neutral Pro Clear",
        "Flash Back Arrestor",
        "Flow Meter",
        "Flux Baking Oven",
        "Front Cap (FC 250W)",
        "GAS TUBE",
        "Gas Batti Nozzle - Long / Small",
        "Gas Cutting Nozzle",
        "Gas Cutting Torch",
        "Gas Cutting Torch - GASCO",
        "Gas Lighter",
        "Gas Pump",
        "Gas Regulator - Acetylene",
        "Gas Regulator - Acetylene Gasco DG",
        "Gas Regulator - LPG Industrial",
        "Gas Regulator - LPG Industrial GASCO",
        "Gas Regulator - Oxygen",
        "Gas Regulator - Oxygen Gasco DG",
        "Gas Regulator - Oxygen Gasco SG",
        "Gas Welding Torch",
        "Gear Oil No. 90 (26 Ltrs)",
        "Glass Tube for 120A",
        "Glue Gun",
        "Goggles - Black",
        "Goggles - Clear White",
        "Goggles - Grey/Green",
        "Grease - 7kg",
        "Grease- 3 Kgs",
        "HP ENKLO 68 -210 LTR",
        "HP Enklo -100 210ltr",
        "Hammer",
        "Hand Gloves - Leather",
        "Hand Gloves Cotten",
        "Hand Screen",
        "Hardfacing Powder - Calmonoy 43",
        "Hardfacing Powder - Calmonoy 63",
        "Helmet",
        "Hose Clip",
        "Hose Jointer",
        "Hose Pipe ISI",
        "Inarc 630i",
        "Inmig 400i Invertor Machine",
        "Inmig-500i",
        "Insert Holder",
        "JK A4 Size Paper - 70GSM",
        "Job Work",
        "K- Max Gold Plus Dia: 150mm Grit : 180",
        "K- Max Gold Plus Dia: 150mm Grit : 400",
        "K- Max Gold Plus Dia: 150mm Grit : 600",
        "K- Max Gold Plus Dia: 150mm Grit : 80",
        "Kluber Microlube GB 00 - 1 Kg",
        "Kovax Flap Disc Grit - 60",
        "Krytox Gpl 226 - 1 Kg",
        "Krytox Gpl 227 - 1 Kg",
        "LOCTITE 574- 250 ML",
        "LOCTITE LB 8203 400ML",
        "Labyrinth Seal",
        "Level Tube",
        "Lighter Stone for Gas Lighter",
        "Loctite 243 - 250 Ml",
        "Loctite 243 - 50 Ml",
        "Loctite 262 - 250 ML",
        "Loctite 262 - 50ml",
        "Loctite 270 50 ML",
        "Loctite 270-250ML",
        "Loctite 272 (250ml)",
        "Loctite 290-50ml",
        "Loctite 406 - 20 Gm",
        "Loctite 415 - 20 Gm",
        "Loctite 495 - 20 Gm",
        "Loctite 510 - 250 Ml",
        "Loctite 542 - 250 Ml",
        "Loctite 587",
        "Loctite 603 50 Ml",
        "Loctite 638 (250 ML)",
        "Loctite 638 - 50 Ml",
        "Loctite 641 - 50 Ml",
        "Loctite 661 - 1 Litre",
        "Loctite HVHT - 20 Gm",
        "Loctite PC 3473 FS Puty- 500gm",
        "Loctite SI 5910",
        "Long Cap",
        "Lugs",
        "M-Seal 1 Kg (New)",
        "MIG Welding Torch",
        "Magnalube Grease - 16 Kg Pack",
        "Mallet SM-1",
        "Mallet SM-2",
        "Masking Tape 24 mm x 20 Y",
        "Masterlock 1kg Pack",
        "Measuring Tape",
        "Micro Fiber Cloth 40cm",
        "Migfast - 1 (P.S.Layer Wound) 1.20mm",
        "Migfast -1 (P.S.Layer Wound) 0.8 mm",
        "Migfast-1 1.20 mm",
        "Milling Insert",
        "Mounted Points",
        "Nitrogen Gas",
        "Nozzles for Plasma (APE -41)",
        "Nut",
        "Nylon Sheet",
        "Oil Can",
        "Packing & Forwarding",
        "Part of Welding Machine - Switch",
        "Peristaltic Handpump",
        "Permanent Marker",
        "Pilot Rod for Gas Cutting Torch",
        "Plastic Jerry Can",
        "Platinum Bearing - Bearing No. N 315-E-M1C3",
        "Polish Brown",
        "Polish Liquid - Clear",
        "Polish Paste",
        "Pvc Welding Hose Pipe",
        "Quick Setting Compound",
        "Refractory 30% Alimina Fire Brick",
        "Regulator ( AR )",
        "Round Brush",
        "Rustgo 250ml",
        "Rustgo 500ml",
        "SS - FLUX CORED WIRE 1.6mm",
        "STUD 20.8MM",
        "Sadar Hsu 4000 Re",
        "Safety Shoes",
        "Safety Shoes (EURO 40,42)",
        "Sander Block",
        "Sanding Belt",
        "Screen Glass",
        "Sealing Wire",
        "Serrated",
        "Shell Advance 10 W40 - 1 Ltr",
        "Shell Gadus S2 V100 3 - 18 Kgs",
        "Shell Tonna 68 - 209 Ltrs",
        "Shell Tonna S3 68 - 209 Ltrs",
        "Shell Tonna S3 M68 26 Ltrs",
        "Shell Tonna S3 M68 - 209 Ltrs",
        "Silicon 1000 - 300 ML",
        "Snap Gauge",
        "Spectra 1000 Ultra",
        "Spectra 2000 Ultra",
        "Stainless Steel Flexible Hose",
        "Standard 25kg",
        "Standrad Electric Drill",
        "Starone Cr45+ Size 2.50mm",
        "Starone Cr45+ Size 3.15mm",
        "Starone Cr55+ Size 2.50mm",
        "Starone Cr55+ Size 3.15mm",
        "Starone 555",
        "Stop Nozzle",
        "Stud - 25.4mm",
        "Superon- 27",
        "Superon- 30",
        "Superon-10 Size- 3.15mm",
        "Superon-10 Size- 5.00mm",
        "Superon-12 Size- 3.15mm",
        "Superon-12 Size- 5.00mm",
        "Superon-18",
        "Superon-1 Size- 5.00mm",
        "Superon-1 Size- 4.00mm",
        "Superon-6 Size- 5.00mm",
        "Superon-8 Size- 2.50mm",
        "Superon-8 Size- 3.15mm",
        "Superon-9",
        "Switch",
        "T-Slot Cutter",
        "Tagiweld Super - Size 4.00mm",
        "Test",
        "Test-NRS",
        "Thermacut Nozzle PD0116-1633",
        "Three Jaw Chuck",
        "Thumb Rule 6`",
        "Tig Filler",
        "Tig Filler Rod 1.6mm",
        "Tig Filler Rod 2.4mm",
        "Tool Holder",
        "Toolpost Spanner",
        "Torch Spares",
        "Tungsten Electrode Size: 2.4mm",
        "Two Jaw Chuck",
        "Universal Putty",
        "Valve for Torch",
        "Vensil Paste",
        "Viking Superon",
        "Vikrant Eutec 8509- Size: 3.15mm",
        "Vikrant Eutec 8509- Size: 4.00mm",
        "Water Resistant Glue 500g",
        "Welding Goggle",
        "Welding Holder - Spanner",
        "Welding Lead",
        "Welding Rod",
        "Welding Screen",
        "Wire Brush",
        "Wire Nozzle",
        "Wire Spool Size 1.2mm",
        "Wire Wheel"
    ]
};

export default item
